# ~/.config/foot/foot.ini

# Set your typography metrics to pull your newly installed fonts
[main]
font=JetBrainsMono Nerd Font:size=12

[scrollback]
lines=10000 # Keeps a long terminal history cache

[url]
# Keyboard link picking shortcut setup
launch=brave ${url}
label-letters=sadfjkl;egetwbyr # Letters used to select onscreen links

[cursor]
style=block

[colors-dark]
alpha=0.95 # Slight opacity adjustment matching your glass panel layouts
background=1a1b26
foreground=a9b1d6

regular0=32344a # black
regular1=f7768e # red
regular2=9ece6a # green
regular3=e0af68 # yellow
regular4=7aa2f7 # blue
regular5=ad8ee6 # magenta
regular6=449dab # cyan
regular7=787c99 # white

bright0=444b6a # bright black
bright1=ff7a93 # bright red
bright2=b9f27c # bright green
bright3=ff9e64 # bright yellow
bright4=7da6ff # bright blue
bright5=bb9af7 # bright magenta
bright6=0db9d7 # bright cyan
bright7=acb0d0 # bright white
